SIL: Use a TypeExpansionContext in SIL lowering to expand opaque type archetypes as part of lowering
As part of SIL type lowering opaque archetypes should be expanded to
their underlying types depending on the context -- the function they are
in. This means there is only ever one SIL type for an opaque archetype
AST type inside a function body: either the original opaque archetype or
an underlying type substitution but not both.

This fixes ambiguities in type substitution that would be introduced by
specializing opaque archetypes.

protocol Q {
  associatedtype Assoc
  func bind() -> Assoc
}
struct S : Q {
  func bind() -> some P {
    return 0
  }
}

apply %func<some P, S>(...) : $@convention(method) <t_0_0><t_0_1 where t_0_0 == t_1_0.Assoc, t_1_0 : Q>

  specialization (some P => Int)

apply %func<Int, S>(...) : $@convention(method) <t_0_0><t_0_1 where t_0_0 == t_1_0.Assoc, t_1_0 : Q>

  error: Int != S.Assoc (some P)

rdar://52706501